---
- hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master
  become: true
  roles:
    - role: k3s/master

- hosts: node
  become: true
  roles:
    - role: k3s/node

- hosts: localhost
  connection: local
  roles:
    - role: postconfig/localhost
