---
dependency:
  name: 'shell'
  command: ansible-playbook ${MOLECULE_PROJECT_DIRECTORY}/molecule/cluster/dependency.yml -i localhost,
driver:
  name: docker
platforms:
  - name: node1
    image: "geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2204}-ansible:latest"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:${MOLECULE_DOCKER_VOLUMES:-rw}" # Use "ro" for cgroup v1 and "rw" for cgroup v2
    cgroupns_mode: ${MOLECULE_DOCKER_CGROUPS_MODE:-"host"} # Use "private" for cgroup v1 and "host" for cgroup v2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
    networks:
      - name: rke2net
    groups:
      - masters
      - k8s_cluster
  - name: node2
    image: "geerlingguy/docker-${MOLECULE_IMAGE:-ubuntu2204}-ansible:latest"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:${MOLECULE_DOCKER_VOLUMES:-rw}" # Use "ro" for cgroup v1 and "rw" for cgroup v2
    cgroupns_mode: ${MOLECULE_DOCKER_CGROUPS_MODE:-"host"} # Use "private" for cgroup v1 and "host" for cgroup v2
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
    networks:
      - name: rke2net
    groups:
      - workers
      - k8s_cluster
provisioner:
  name: ansible
  inventory:
    group_vars:
      masters:
        rke2_type: server
      workers:
        rke2_type: agent
verifier:
  name: ansible
scenario:
  name: cluster
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
