apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affine
resources:
  - namespace.yaml
  - secret.enc.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
