apiVersion: v1
kind: Secret
metadata:
    name: affine-secrets
    namespace: affine
stringData:
    postgres-password: ENC[AES256_GCM,data:nW0wLcpS3cH3GZnjb5p8GMVHwS8=,iv:iayOIbgl/PrKtKsOt9v0BzgznkUZh7f3LDxi5fYKY2c=,tag:JGIzITWxsjtpaKCw+St3QQ==,type:str]
    database-url: ENC[AES256_GCM,data:oPWCnG4/18f7wLyeN8ntyyZgzz896D4U5M/POZRUqS0TYC6LwboeWTdXe+1j7Ljx+0x1bLG9DqmUanHXSX38O1oqA7uzFJaWiV7q5uye3g5B6Z7SjiNSz4UYqK9+,iv:iLg1NO03n7KszEUWpEQiXbVhwy3tKzXiv5C+6t7hEDQ=,tag:KS14GWAfF47BUeCxcnR76g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG1sejBMdyBBeklackhx
            UXpMK2JtUUxZelMreTBrL2hIQTBlN2E4T1ZUcEZPeW1sZnVrUgpKMytLZlZpK0Fm
            NEh5ZTAzVStIR1FMVXFGSXFTYWsrN1pZSFlpTjJ1bW5FCi0tLSA5RnZmajhDOTE1
            UE4zSzYxYk1UNmd6SkZDdkQ3eEJ3dlpINllNemtGVm8wCgUptGPWqfAn9yrKJNWH
            mDM39bhqozcHaG1uHKJgYR0EtbHWJ6usNDKPm47qXW2EFWY7UuoOqQFqkIYSiu0y
            +dc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qddeulwl9jyv8cs7hrjnfr9c3kzhgs37rgzuqe4ckfvuxwpxjknf5w28ysw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VUVZcllRcnpvNXFORi9m
            UW5Nc21NUGNzRXJLUWZRdm1kQnRHUlhoN1hZClMxWmxhTUtlOEw2QVV2M3ZaeGNK
            OXlCSEluVUNUNGxIcVFOU2MwbTRiNmsKLS0tIDlzcWlsWEExUEtmVVMwZE91ZjhK
            MDQ5MlJiVTFtaVZhNm9aNHB6UEs2OW8Kg9p3kQ6b8wHBYj5toXuYLJah+oJXTPbU
            jRu8Tn4WtmDe0RFbgBsbtA/dHZ3r3/4eObMpgK8zvFU+vj6HIBYckw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age155wgqqmcj5gtlazttmyn8uknp6r7pd3us90aqe8xq6mhhmqansnsx6a2aj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T15:05:35Z"
    mac: ENC[AES256_GCM,data:KrqUrVHaUH0MBo1dmTF8QnXSEgb8LuTTBNaqpST8jTa/xWgbRY42e/knkq6v9dh/DqicRCv/zX6JQcsO5dA3Bg5BQTsi10knppKdt64KPDAz7+buye/ZkbKzV6+Y+yKZzdil6+y4IbZ2Ml2HVGa70VE/eLoDTJxFPhpR1F6Zpm4=,iv:bhqohSKzNdI1j1Vp8V5ZsvGQGzNLjfDJzSKLQ/XqWY4=,tag:CFzJRPfnlIsHq1mWuLU3rg==,type:str]
    version: 3.13.3
