---
- name: Set hostname
  gather_facts: true
  become: true
  hosts: rke2
  roles:
    - role: hostname
- name: Deploy RKE2
  gather_facts: true
  hosts: rke2
  become: yes
  vars:
    rke2_ha_mode: false
    rke2_api_ip: "{{ hostvars[groups['rke2'].0]['ansible_default_ipv4']['address'] }}"
    rke2_version: v1.29.4+rke2r1
    rke2_download_kubeconf: true
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
    rke2_cluster_group_name: rke2
    rke2_servers_group_name: server
    rke2_agents_group_name: agent
  roles:
    - role: lablabs.rke2
