---

- name: Add Jetstack cert-manager repository
  become: true
  run_once: true
  delegate_to: "{{ groups[k8s_servers_group_name].0 | default(groups[k8s_servers_group_name].0) }}"
  shell: helm --kubeconfig /etc/rancher/rke2/rke2.yaml repo add jetstack https://charts.jetstack.io

- name: Update helm --kubeconfig /etc/rancher/rke2/rke2.yaml repositories
  become: true
  run_once: true
  delegate_to: "{{ groups[k8s_servers_group_name].0 | default(groups[k8s_servers_group_name].0) }}"
  shell: helm --kubeconfig /etc/rancher/rke2/rke2.yaml repo update

- name: Install cert-manager
  become: true
  run_once: true
  delegate_to: "{{ groups[k8s_servers_group_name].0 | default(groups[k8s_servers_group_name].0) }}"
  shell: helm --kubeconfig /etc/rancher/rke2/rke2.yaml install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true
