---
- name: Prepare
  hosts: node*
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.package:
        update_cache: true
        name:
          - wget
          - curl

    - name: Install special packages for RockyLinux
      ansible.builtin.package:
        update_cache: true
        name:
          - iproute
      when: ansible_distribution == "Rocky"
