apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: cattle-system
spec:
  project: default

  # Source of the application manifests
  sources:
    - repoURL: https://github.com/Vinetos/infrastructure.git
      targetRevision: HEAD
      path: k8s/cluster/rancher
    - repoURL: https://releases.rancher.com/server-charts/latest
      chart: traefik
      targetRevision: v26.0.0
      helm:
        values: |
          additionalArguments:
          # Configure your CertificateResolver here...
          #
          # HTTP Challenge
          # ---
          # Generic Example:
          #   - --certificatesresolvers.generic.acme.email=your-email@example.com
          #   - --certificatesresolvers.generic.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
          #   - --certificatesresolvers.generic.acme.httpChallenge.entryPoint=web
          #   - --certificatesresolvers.generic.acme.storage=/ssl-certs/acme-generic.json
          #
          # Prod / Staging Example:
          #   - --certificatesresolvers.staging.acme.email=your-email@example.com
          #   - --certificatesresolvers.staging.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
          #   - --certificatesresolvers.staging.acme.httpChallenge.entryPoint=web
          #   - --certificatesresolvers.staging.acme.storage=/ssl-certs/acme-staging.json
          #   - --certificatesresolvers.production.acme.email=your-email@example.com
          #   - --certificatesresolvers.production.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
          #   - --certificatesresolvers.production.acme.httpChallenge.entryPoint=web
          #   - --certificatesresolvers.production.acme.storage=/ssl-certs/acme-production.json
          #
          # DNS Challenge
          # ---
          # Cloudflare Example:
            - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.cloudflare.acme.email=contact@vinetos.fr
            - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
            - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json
          #
          # Generic (replace with your DNS provider):
          #  - --certificatesresolvers.generic.acme.dnschallenge.provider=generic
          #  - --certificatesresolvers.generic.acme.email=your-email@example.com
          #  - --certificatesresolvers.generic.acme.storage=/ssl-certs/acme-generic.json
          
          logs:
          # Configure log settings here...
            general:
              level: ERROR
          
          ports:
          # Configure your entrypoints here...
            web:
              # (optional) Permanent Redirect to HTTPS
              redirectTo:
                port: websecure
            websecure:
              tls:
                enabled: true
                # (optional) Set a Default CertResolver
                certResolver: cloudflare
          
          
          env:
          # Set your environment variables here...
          #
          # DNS Challenge Credentials
          # ---
          # Cloudflare Example:
             - name: CF_API_EMAIL
               valueFrom:
                 secretKeyRef:
                   key: email
                   name: cloudflare-credentials
             - name: CF_API_KEY
               valueFrom:
                 secretKeyRef:
                   key: apiKey
                   name: cloudflare-credentials
          
          # Disable Dashboard
          ingressRoute:
            dashboard:
              enabled: false
          
          # Persistent Storage
          persistence:
            enabled: true
            name: ssl-certs
            size: 1Gi
            path: /ssl-certs
          
          deployment:
            initContainers:
              # The "volume-permissions" init container is required if you run into permission issues.
              # Related issue: https://github.com/containous/traefik/issues/6972
              - name: volume-permissions
                image: busybox:1.35.0
                command: ["sh", "-c", "chmod -Rv 600 /ssl-certs/* || true"]
                volumeMounts:
                  - name: ssl-certs
                    mountPath: /ssl-certs
          
          # Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
          ingressClass:
            enabled: true
            isDefaultClass: true

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation

    # The retry feature is available since v1.7
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

  # RevisionHistoryLimit limits the number of items kept in the application's revision history, which is used for
  # informational purposes as well as for rollbacks to previous versions. This should only be changed in exceptional
  # circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the
  # space used to store the history, so we do not recommend increasing it.
  revisionHistoryLimit: 10
