# This secret is explicitly exposed in the git repository as the infrastructure is open-source.
apiVersion: v1
kind: Secret
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/Vinetos/infrastructure"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
