---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.9.3
  - ingress.yml
  - argocd-repositories.yml

patches:
  - path: patch-argocd-cm.yml
  - path: patch-argocd-insecure.yml
