---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgBVIX5BvXedhdLeABKqmVHaTiqkWslEOGpcwgaQqnT/g5G0SD3PGv2myvpXfJFK/mPVzSBSmqY6fKXytvlb1aYli4CEP52Py70N9hH43uh28xJFkRj3Z69Tk2x0JKw+QkzkNO38uzcU7Vuw1PwYe4UxpyYPfQbG1wnThbZVpFesMVGOsTbOTUWNRWJ1R0AJsYbsuLMNGBi0K6Uao/LSjCyPrrFuA5YMziEVd+D5Y1/5JTpJDyNQZbqKFfdObwErISN0lTL0vio/7BRSaY43yzMT1Fd1kjLb8qXXB2YhzvE1PiNPeSdXT0TEcmxvAlEiKS5dzICe3XJdsuolF2p9Qdo6QfmAi4jI7Vl3wjiRHJ3wFzDeRClpvPg3IBX7Zsd0eUxxlo+Aqr8LWPh08TuKK9DoJZ6HB6QMAGMi3L/OzgaR4f8vbOPo0hBjMY1tS/qr9le2MgPvNr9ak6PrzCc5CO3idVH/mYtaSq/kUsbcFF9y+f3kq44wgKG5CCYlfh8Vc9PVta/U2ki8/qUOV8mtmIrQ8tf6zVS7ae6WzcRrprhaBhPJWoGjHUk1KQ5WPLTtjm8JJWxtZQH6/6DTthhbQDEo8neymuCNV8ejXFO025FLsBYLb6ERIxU6Ro2Mjrizl+s3ZQ8+BdMmx8DKQk8bg2vGhYwEtieUssFH1pHj5jRrL8s7Bsqi9Dd4kcrQc9vc6nvVCNHKq/IrtYHlB2bXrSKZrjhgWVDus41AhYQxqmfiTOHyIQyx
    email: AgANPUUKPVSNXKAVcoG4UMyKOlIwps1BWWzyQWDFZO3YxOlJSvahUf5iBGZb4k0L5g+QR8eBF7o8PJ+dK70aI9oIcleBGEgdAou4A6U63AUJT8rIrhxjxnkB6/iVc6WnVnHa40BR7gQtB/2/E1fVdIUFMtn5gDC4WwnzzMO7si35iE3fpj6NmKhXYFEkFYXqrQq97+sFRJuf5iYApNuNrlUvaGR5vACu5AcbrpTEwKv4mgyNfmw6BQ5D/cZjY8JOyOy+OTwQZErvHjZS08oq3VM0cm6wCp+lO5TdVxiCLDDA3DCs75K5eWNIjKoRgbbCHdX27Z+mYtyeFSggIrokaqVpkfADBqp9k2afS5XgVCVKz5FTHmjYLjPfJ4yldWAEW8lkyfTorCz/J81tze2JCGyVCmWB9osbwwnQyrw8UGDmdr5r3et1OPeq4k8IwbVmnol5TKgQsnuWAnJDeACBnP5U3Ur2AiKcp0GtPNIYvrd8dlWCwcko3zJsBQwvDwlYFXu3xV8DCX0wrEi+sgcVn09GeL6igTUkbewtxlz2txxnFHEFXKWnGvZWrR4f/9juhdtzOwiXCbkOhxtzPocOqv91X2SGf0telEfd8LBQ2sEjl+mcq7wmJ4Rsyta4ywx9XtoH90+1TW/fWRHfEiVtBvNgGjlRKLv2C8jLqRgPL3AreFiRq5c95NFwRwjTEvZLwuy1ieLnnEidcXW6EePVnUUWXIracg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
