---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgCBax7S74e8kA2ca9AOCsT0ZrJlUbgjbUae4o9gxqUrIuJKJ0snPwLGyDrF5YmCSJZ+kcUz7yWXx3sIcxq/Qy32fm2z/gzflxpJALWZpsT8gtmkE8Y8NiXY2vMYsCcnsy196PmNVa++vG2R3n44nCS/oopOSzBTXTRAG16vDrF4RsrUXTYw+EfenVIumb1Mt0SrPNjOIoIftlZ9Jfu0jGROFZRhBG1YN/IfAL/VqnWvywb1HFn2YvCel3wnNIa3L2zJsWhXy4iI4jEbf+EAzLsFwzB7J6Ys/YMnc1YhTtwqJi/MKwE2gcnFm7CzZHp4ihgK7MQ8phCpI9C4eAsktGADOgh82klZTjWNGdN5KHse8azqvm80nqx6BfPo8qWP+5IJvTkq/IKDrP7+5Is4k/dqfVr5Cm8mpPn++Z3MFrxLMBxuD1lgJ02Y4C00dE3Mz6yv+TnGrg0SNEGh6VdCnvJMWNT+xRp9AypuI/dFXs2sZO6cxAqANfbU1U4ayTOiGYm33jRVoceZkGvpGW7yEv861upcwP1mFfWiAaalSzZ//LgZCPyrQ6YpyjZuhdSogTUC61kUylweg+uT1HdKE4C+zu+0CwuaeSis9SogaQn0wvrYki0fcUxUiYVjzuteVzK9V9KWBsXZA34uEVkYwGZzGT/LbKFIIOuv2MWAxNdaKBpNhz6BqxHSsmK1JBfVsxh7PZhNFwb+kc2kL8sH2SgNeHDLsGKn2btv34yDBEWRnvFGuRCH
    email: AgBVjaRl2A8+J4L06ZDcUwCjZGwIiRuNaKbpaxhwVCdzuTCbrCI1kwwPH1CnhMIetzE8qTyGHuYLN6lHE9ifB16Kenw3b/Vl30HPlSXxVEcbgUt3kRFgQ6gT76qkJe8oKSiA5kLKhCZ/C9zdpcVZS1PR7scBMDBOsrwFB5NBlaex/TZOfl+xIet5LmBrEii/JqAfhWntdgrUOEelVjbT4gnQgVnaCUdW6r3XI7zbDZiRZ+1ffHkA+qSvprhuCR5A3EaUbAaB/yOkdgEwCVta9Ebc6TzzuVuTWkv715DD+5Bgz0xB0tbROjpuaRGnjCO9lxcFG+2GEtuHwSWbWLhqUpUAfT4UzFWMP/+chMyyvZW3nroC11jfoQecSaM8hG5AZiOFAuzrAGPYbABgADiwZhBtORiFYYPgdyMoFoh7f9BjK2Y904VhML7FlvmzjJf9xkDZkNGbGOkwxz0yZflM5gogCLse6DCsCoTHTyBW3muS+NicPfDfYkhBfr/d4ioXhvSPOo23liPHkfKgOLbOFkJLZ9QN30sohfaB2avYbgKbde6JW+JtsFSQ34Zpi0uClzhFZmwIk7brXtaSu/jI+/kD9r/FPBqNAGUSMpWCHX09yyTUunPFbB8/rR66Z/r3z9RJ0STPOyqatjqebu/R1Ol5/F0iQZF+YI8c6bhk7O/1eXeE1SRIGQpKIekla9Wsyhlm999xKk93WjXSo0B89sFRnhfu/g==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
