---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgAPMFg2bwwi/4yNz33LSl8AtangT5IRm3T99N0C/ZGLTL2LDntxUyqScrbmQzwLA4DjYAMZf9pw9XJUJDVOX/gJVatjeUZ6W+/tVRexw5CDEx2R//ln0kt5wOWMsXQmaRRTbLGpNuGQoaB+Pv/kNbf6dKYbXqPMMs1TGAcGj8/SFO1woQwy8e+svGxhc4t3Flgff/xpB5IDEvdTnL2IAmFHA8B85AUiciI9tCXJX3MckCM6nvP/rzoOZtVmCKmVJbL3Pi+UxxvQr8QxYGwKx3lANgo/1THG5FAIbUbL+ev8X6amlXWBAU76gW6OtaOT3czGIYHg/Jgw7IMHLOSL6f1nZBJ7UIOkTeewsuEBVJcsul+mX8OAFfPbSJZK2F9/5iIwe8lg6GV5KS8DhaqMxXyUz17QqEgmcTqO7mf6mYCmK5X8jicnCnku1QNRzqHhU1C1czDgfx+ZwDHK4VSMs+XNV1FtFMN1A91uA/s+DTPJofxNXAx0k7IYTgv6ZhCKp/cSQiJYuz9ZsOb2rfSbl43fUiOB3zSipW7C/Q+oxK5HI3bXOrV7QXu6neN8ZilI8Q3V6sMiTefjwnhcoQ/MDD1wydVdu6AvfFFvQH8NeBrp7cuRmptHhqXMKOPByJHc0n0LIUJVKUUte6/wj+Kf7u3YNZLxuGw0rENKwC9wKqOtgwBW2Bkvw2g7fRpAWOjKB7WIVxjkKEAYVkXlYbQv4MIREYnbrvungh1TRSGtColcfWa6vtiL
    email: AgBrzHXK7We0jPtCxbLaGt8R9y7LH4q2y4SX2kNCDt5nmp3ZrJfqQb9i7pE2KFvXW4FNNj7hASS04RHkeqtfdM9CQDr0ljzIZvNo/Yw/B33Rbe3QoS6tjb0EB85vbe17mhfBjl/oKG55Jkru+FpA/vnW6nbEMbHxy/3ICBgUrAasXyHBi62ggHUmd/pUQxm7ZnM5c9Q+GrmLV+iL/O5BpwYcKBSqSzR8CdqToB119pI+d2YjncOyYpGwoxlPVN8rlKsv9T0wFTloJDTupFh7d001q55THbnLsikKbWh7YwBARtxaGQlVCa5ywDqzgQNosDt06n9ssYbRBUNZzDEdfKBTb/lWW91jF3YQPhC6WbB+Xj3BDimr5Ws39wxC9AF6YlsG/y761YCEPwKY2hLgiFHKu+dMieVfbWkUN5TK17OhixckyzR272H2Dkz6hsOkfuoBVDcYdMohOK+yjOivhJWMoZqplqlkrRvghrUUsQt8EgYR9da5QRea36mpaFt0KEBtT+BAzC89xKPBEXWRGBxh39vXrTIlmeUjyy6wO+EghlO1bEALcsmOTCo1yi8SFH72u8+8fN9q3ITSP+9x+gPENwmF3WdG52HCm6bSxAyCMucnQGmHeFiIcwnKoxayK0vdJYsmLHwIqMRoV+QX+MZ8TCbOixtTU1mkEiubjbnEKtxNT8E1ocBbwJjUP2xIjRkNhmc1Rck5Hdsj6eTnJU6CU4IKlg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
