---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: AgCFWmUo+kmgfz3o4tfcNKdh+hGIq1Y5SQ020w+/TtMe5L/mwuYCApqJmgafX1jGkkOGhyXVCoBjU35QR6K4S2xUYz5eelGVLBULPkHBSv+1EHF2VxeI6p3dJ6WS+xHHmgKbjaL2lFOTpwr5Drm6Im5M0+1nuxzcIDAVYtuBeCR3DtiYaan5TI4dsWmA7WLzRbB8soNkkU0DYjQsOWAtJRJFRHlgVgUNaDPln8gLMgJgm4iAnbZm3QPG2AAkabj6TDf/VZMHNVsAtuiBFBMpit9AnWZxMZvVlJQ8ct46hSHMDgKyS66+wsqRdC/7ecbeghCABb8jGGUlp/qG0bxpuCwPcmWjZmS6JLQRSXmma83LFNNKcnNUTkw5jVfDkDa93fKarSS+Ep3dBGjtv12uEJWECJWqmwjTN2GJD96ZyjRtnyeRyvFsbU2fYQRf1DOKerr/bbAOVEUevL30iV4knr1EYt5EreXQNCKf/DcRWjDDIw8fBREX6S/cvLNaLuzNfXg856/2mvuAw4+0o8A4EqERjipn3k8YfmM4l9Kzqfff/TmyNGwFNxkbTnuN8Qcr4D8wwKdb/Yh+MjWTX7Y1lGLsmuWXuCBgLEhLvzGMLx6Hax4BfRYKl59CCKusJ8jN5Aq5nmw/Z+BZxD5H52HzklBNVzP4izN9hDi9KesbWSlafTcg+eDFNZGRN6NguDDCYUCaj/C3Kh+dkH8AeQuhe4kCK5uyQiLo6TE9SKobkWVNH+3U/E8B
    email: AgB81ypTwxrfkYrZ4aWgixaSXeQ3P5TjIXnJvEsDvNHDTskyLy1XrigxwAaKCwSxfNWci1M3sFNDjSJUl1550BPnS7d/3ji3c/rgBE9nWTdCF71+mzg95lI0MX4FFkOJutoL05sI8CFL8juKVsdXtF2LJTV5Un2ZqBS5nPwO+JZaoMrmB+aYRz6GWcGYAD/kY6r1uwPT2Q2kIswjigS07doiqwKBXBQuQxceUKZgCMgeGxTrGso+O616C8cPLl/BJ+M1ou6MThSO6BSegQS44N6C2koRLYlrQbcaaP/4+t4g7zTK+0uB8SChFGahhd54adxRjqcr/4XK9HMCofDVJv3eqgne9XkfTYAAiHthEe1gKsc2BqZGMQO/1Br4Wzen71SBEnC07KZx9CzphaJn3iDovdW7qKFzBimHy+IPwS+ZaOPed+XlrqsNEf43fL3327VfYpALHTIkDRx2B+eaml/TpTdo0pZSUVQYM8KcKMWzfJyZ3edonJ39abmwGKrVoebq/ubGWqkSU1BwaVlXNLeykGzcEgWTBzSd1D4ve0hXSFkibyyuruHNHjsMGsQuzI/ipw5Ai7cdAYm11vRSktxSU8J6LGoJ5ggXAAK2ji1Smmzn29yIyCOo+Cq78WJ8M3Gf6s9KgUNxD1UFDfFmK8g9DmF8QL9IsdChB/os4fPvHMDFH33UN9PCKIEosjieP2iUKJLitbPmoU2p2O7FVHvsIume
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: traefik
    type: Opaque
