---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: kube-system
spec:
  encryptedData:
    apiKey: AgAz87k5W1Lmd2w92yqL3yfyLA++lQmiBseMsElF0HWK2wPhLqjGh6XvvbVyxOggWGQLdOxPJ37lsqLBeh+6PY1syj77F9OncfbyrizmOHbF8Qwzu9Us/PJ53HVjf9SFUettLPNbLnqwo4xn0q84KkMFrRZiEHcZR9X7XB+krkfcsdljwArMgfewgOVPStDTQU7EdISFrezHWQxaT8olT/matR1cZ9YWE2Rn/6s+KEb9bk3prm1yvBzUyJvrYcaPpYk1vjpk5o/SvWF+26Ly+V7DnzCvchbcA2e75r9RqpaRumbNFW30VDX4f+msUkYqbNANmdp/7RaDyyPlIU30QPGhvajQIS4VKY8StRLsnTO6nm6bSqtrujNRkxBnsO62CZfJNOWzQquv39q3btMrEhy+lLbFNcvkrnyxAYTKTM22Qrp5vqHR0Ykv2vjCDRNWIfO2UWYuFRnPXtMSQJedtaaZoNzikmubWHZLRL+HZSKFSnBobqboTupVVt/aA1pBgqZNsFTMKEACTtONkTQWMY1jCPd6UWDhDUw8NwFF0K7ySayxrhEO/f0lHL7UTvT//sPSBCX41CryYaaFCFmQZMnWr3/QCmQuWqawea5HOcPgLTIYaxuKW9bLg+bh3MQiI2N7gfdhuYL5JZdA5StSSU9x8MT4/eRYZtzlQV2SpSu+fFkYIb1IGu00sFs7QRqQDHThsWmFCmalUNZAlq7m/YWTGCtgsJHmwVoe9Hs3Vo3GdD45HyX+
    email: AgBJFe7yt5v9bsLBdYCGPLhDM9AtAKMb9g9Oxyzdq0Ui/3XwlxTjkc6xWa/N3qbBXbZGJo/OFuXKQ2VWEZSqFtsHXaWY9u2yaXOXHEuGyZPmbeHIKmcbPxg4C+irFPwmjql6JgRZSMsTCHGzHQVI3+f6pIfJeJFRtcKcI6+xxG2hdcPSxvGyfPUsrd4NJ34k+/jzsJRyjfFp1oSf/7LZcBm0eLLS02SvYo8DYJ+xb261Ef+O8LbKeA8dipPMgsd4CgzYAyrP9XT7Tw4lQ1t5TIFzn/SEC8nR+FXrKic+t2YGOPdjHtDi9DlMcofsuZUTSmtCeGLXEA8/6uK0Pg9EQAvihXGyCI+rXhhUaq1z+37oojdnUwygq66gQcw8os8uUpqbV8GKbEq9brq/lfwW7KsLa9NKK1W2wyLCfmBHgOWgA5XWMIYA1mszkduFWN75QIZQnCuoVtxC+Z118lvZYCYYKANPOg6ONBFgVcyQDeIuQ1CxlylOXx2smxBcxHisQNLBd/JJ4FvMyu2wz0TjpaQmk32nimE/+bqtmw3VI8RACsISqJMY0GT+N0PpUPEkRcd47818EY0+UpFemfDhWWD09g4D5V0p+lvMe2w9qrcB4YSXrSYFKocC5tT3vaPazd1tva4yKkPfQcCfyVqLBIa8ahtM6e6u18hUyGy8+ItBPJBtEsh94TydKIi9W5I5pJ3ZDgWZ8Q5FEbuXf4K0yTm4nnmIJQ==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: kube-system
    type: Opaque
