apiVersion: v1
kind: Secret
metadata:
    name: sure-secrets
    namespace: sure
stringData:
    postgres-password: ENC[AES256_GCM,data:RMABdFNK5jhbh0nTwlos5J5QnL4=,iv:vsvSXngK38N1i60LvVN68WaojvKC8QtcATcEruDH45U=,tag:lfoVzRtcdBFg98t7KVzfmQ==,type:str]
    secret-key-base: ENC[AES256_GCM,data:ycn/E8tzbdheyPRkthQp7OGvVrn8nAG4y02tB7OZoOKlClo0TNXuPqFiaHSMKbCYLyhct8x+iLFDVOW0xHestp6PkQUvrSl05XojYYf/YvPDuYZPA/jtdBrDRnjD5hV+fUkB/zb0S91KKLE4njzw47HiA1zS7oCt6x3UZggOEeMe74N7O7jw,iv:5GkNse+i1inS/hH9NehvVyEsz6AxBYA4uFiOzEE2VZw=,tag:uMar+JXr/QVx2hgkOuOdgw==,type:str] #ENC[AES256_GCM,data:Q2M00v7t/v/oeJCNDLoGfxmKnB6E,iv:qRJdRP7HDWciHJd6ETU3X0SXhABEEFvzkQSpPji/S50=,tag:47PfPSvbG7bsliFRtrZ1cw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IG1sejBMdyBBOHlubnNi
            MkZkUmliYTA3K1J6bitVR2tHcTViSFRBc0FhTlVqc3lEdVhjbwo5em9VL1NLZFFr
            SFN1UWF1Z1MvYXROak5MbmZUYkRYbHc4MVlpS2JLU0x3Ci0tLSArT3FqUEMzbCt2
            akhsUUpGSU1FM0gwTFRlLzdtc0VTTTd1WEpBNWZQaHZRCi/CqIOftrEfRG7i24Rj
            fqfDvkUJA4ft57jL8JmpsAzG5YQDQeDaHanl7VUymISIupZE0KE9DZEfkoGzH6ay
            gPA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qddeulwl9jyv8cs7hrjnfr9c3kzhgs37rgzuqe4ckfvuxwpxjknf5w28ysw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQVFXc2dXd3NqRVhLcmQw
            bGJ3a3hjdWpRQXF0ZCtmRzR3VEtJVTZUakY4Ck1HRkJqSTFnU2V0LzVpNTFORURP
            V29kNlRWVm1qdnUzcWROOUZXeFhOWUEKLS0tIEYvb3NaT21OMXFyeDAxVmFLWGwr
            OVBWQjdwTitheUNBYjRYaUhBUmRkaW8KINaVMGiyBcMVR8S/uA13Z9YgzPAPFux2
            jpGBofKEu5LwFg2h/HzF5bsaaYH51/EZF5NW6sLSIR3oSuN3eGm9zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age155wgqqmcj5gtlazttmyn8uknp6r7pd3us90aqe8xq6mhhmqansnsx6a2aj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T09:28:59Z"
    mac: ENC[AES256_GCM,data:dfL3xrunszkJ/hxbryD6iQ5IWQ6aSh6OIXnU0wFhSOfGCyqA3CWRTt2IySAALla97GK/BueIWpkqz+jfi2wPSIz3X8WJGBCYaN8GQ4o9daL1LSLgJZXIKYGE9TR1zdb6IzqyvwkqvuEi99ca+kr48fihEAQqFyYzQgoTYtUVG0o=,iv:sEwMaGPXd8vpJCn+yNDuvln9pcEc8ay7EhpVYYlSszs=,tag:Kx2s9TxxS3U/OYRuXP6ZtA==,type:str]
    version: 3.13.3
