apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/affine
  - ../base/sure
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
