---
- name: Install Minecraft
  block:
    - name: Install Bash
      become: true
      ansible.builtin.package:
        name: bash
        state: present
    - name: Install wget
      become: true
      ansible.builtin.package:
        name: wget
        state: present
    - name: Download MC-manager
      ansible.builtin.command: wget https://raw.githubusercontent.com/mcsmanager/Script/master/setup_en.sh
    - name: Run installation script
      become: true
      ansible.builtin.command: bash setup_en.sh
    - name: Enable MC-manager deamon
      become: true
      ansible.builtin.command: systemctl enable mcsm-daemon
    - name: Start MC-manager deamon
      become: true
      ansible.builtin.command: systemctl start mcsm-daemon
    # Panel
    - name: Install Panel servers
      become: true
      when: inventory_hostname in groups['panel']
      block:
        - name: Enable Web panel
          ansible.builtin.command: systemctl enable mcsm-web
        - name: Start Web panel
          ansible.builtin.command: systemctl start mcsm-web
    # Valhelsia
    - name: Install Valhelsia servers
      when: inventory_hostname in groups['valhelsia']
      block:
        - name: Install JDK 21
          become: true
          ansible.builtin.package:
            name: openjdk-21-jdk
            state: present
        - name: Install unzip
          become: true
          ansible.builtin.package:
            name: unzip
            state: present
        - name: Create user
          become: true
          ansible.builtin.user:
            name: valhelsia
            state: present
            shell: /bin/bash
            createhome: yes
        - name: Create Valhelsia server directory
          become: true
          ansible.builtin.file:
            path: /opt/valhelsia
            state: directory
            owner: valhelsia
            group: valhelsia
        - name: Install Valhelsia server
          become: yes
          become_user: valhelsia
          block:
            - name: Download Valhelsia server
              ansible.builtin.command: wget https://mediafilez.forgecdn.net/files/4978/44/Valhelsia-6-6.1.0-pre2-SERVER.zip
              args:
                chdir: /opt/valhelsia
            - name: Unzip Valhelsia server
              ansible.builtin.unarchive:
                src: /opt/valhelsia/Valhelsia-6-6.1.0-pre2-SERVER.zip
                dest: /opt/valhelsia
                remote_src: yes
            - name: Remove Valhelsia server zip
              ansible.builtin.file:
                path: /opt/valhelsia/Valhelsia-6-6.1.0-pre2-SERVER.zip
                state: absent
            - name: Set run permissions
              ansible.builtin.file:
                path: /opt/valhelsia/ServerStart.sh
                mode: 0755
            - name: Check for eula file
              ansible.builtin.stat:
                path: /opt/valhelsia/eula.txt
              register: eula
            - name: First start of Valhelsia server
              ansible.builtin.command: /opt/valhelsia/ServerStart.sh
              ignore_errors: yes # Because it will fail
              when: eula.stat.exists == False
              args:
                chdir: /opt/valhelsia
            - name: Set eula to true
              ansible.builtin.lineinfile:
                path: /opt/valhelsia/eula.txt
                regexp: '^eula=false'
                line: 'eula=true'
                state: present
            - name: Allow flight in server.properties
              ansible.builtin.lineinfile:
                path: /opt/valhelsia/server.properties
                regexp: '^allow-flight=false'
                line: 'allow-flight=true'
                state: present
            - name: Updated allocated RAM
              ansible.builtin.lineinfile:
                path: /opt/valhelsia/ServerStart.sh
                regexp: '^ALLOCATED_RAM=.*'
                line: 'ALLOCATED_RAM={{ valhesia_ram }}'
                state: present
