---
- name: Install ArgoCD
  run_once: true
  block:
    - name: Create ArgoCD namespace
      ignore_errors: yes
      ansible.builtin.command:
        cmd: "kubectl create namespace argocd"
    - name: Install ArgoCD
      ansible.builtin.command:
        cmd: "kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
    - name: Wait for ArgoCD to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 8080
        delay: 10
        timeout: 300
        state: started
        msg: "ArgoCD is not ready"
