#cloud-config
package_upgrade: true
packages:
  - qemu-guest-agent
  - fish

timezone: Europe/Paris

preserve_hostname: true

users:
  - name: vinetos
    groups: [sudo]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /usr/bin/fish
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtVM4VVm/4N6rYHcAxfHoiQPs5v/Luj7fTjct2541/YuUUTtA0OQ4BbOsrOVQgjxqXyr8IMYjIODAfS4DzurEvT4R95IEvvXbsvkxzbA3IgLPoF76xoehI2U42DwVOsmnG4l8RZPQu4NdfMOK2XIaQYau9UCj5QGZcu8bBTXjwsa50JHHktc6mfASFtTdZc5AAx5g/PDpQf9QA/jrpSpWtYej/e4uhTBC3YK93AtLjvKVvqmW7hXNM32847RbuAs1qmF7QgGa5HFn8bVTAVFIFUG+J2VeftgOMHjqKmwxZdN+gIVrV3rkusK7qBUESxwZ30bq/xnpaFrnnQjX4TvtxCcqdscN31lipTzerg8B1GAiZWWEBG0tp5/1+0GbYgGwdPQDt5xaYAYv+bXyAwSCt29QptCCFSW/pSjZ43sC9UEbuphJGXcL3BYUTjxSut+yyf0Dt+Kclrwsyyf30FLcR35hoSElKnHgjQiSU8W6lUgNo6aFgXOoevtxMrKuHErq6jroDXJGkVn602ufKeW2UwthA5yBnHKt5GWiIqGkGA6wENS1520EqvOAgmcKBZMgeJI+6VjXH6e4wGBAXPL/5VgToB3gpxuO5pkjF9Lu0u6t/OiDiksFJa2IghpyII22YaqWks9L0+dgz7pwUYntHvLotn2Y2X7ma/iJLPEzm2w== cardno:19_667_061
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQEAHu9Td7bRxtdzocnnKjBavBEl8WYJT1fs6Rq5yN7Q3s+ZKoNs+CeN8S9qwEpz1dE2Jh1pt6VKPMypewFrgjw22sdauDoNneCaPltvtw3VjIY/TnEnsq1QLj6GD23UejbuWqaBjug2Ov4yj2rVFUwgA6iqPj66sZOe5LWp3F8ALmvqd0eS1769f75CpPX1yZl5cXg4y/uiX4qhnv0QiPCo3BM03oPAhUZ0zV9nc506dFjOjNLTpQnJJWKrqQ5/yK53uPMMpiV1WrYEb2QuTbQpkhaXoQUju1Q2HNlt1fitJrsp+JMz9uyI6MwaOH3gJtyT2tvDzGYruCn+e5sBKOCfnatUtVdvIm5kHulCAwOfPs8sQB3KLljECew/zfjsMhW9+8FknZ2zzRrtcsw0h+fYwdYwq0eFjuzxqp1mzYUyPlQKY9Y9Bjlea+vNXMl9LITg0kExuhPoFDK7tag0wpPFhglirg1MjgfLf439pgI01DiDjGmrTCH3x6qGtJ/rY5ic37puXt8EiPbcif4Bhkxsi9ZUruDzsyuILamwGGSQnwipCQwqKZjDaPmviU5KCQcsVmwEnuUVk/TeCrMEGpAq1pRxzcirtf/ikkgOhBrI8+2ttD1/tfvzbOK0Z8SgklT6V7G2MtWiqfWxhGxFqeKbMPnjLvndcX/xwxkukHCw== cardno:5009786

runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart sshd.service

power_state:
  delay: now
  mode: reboot
  message: Rebooting after cloud-init completion
  condition: true
